### ISSUE TITLE
How does this compare to AloeDB?

### ISSUE THREAD

**Issue by cktang88** [denyncrawford/dndb#16]
https://github.com/Kirlovon/AloeDB

**Comment by denyncrawford** [comment]
**Short Answer**: We was first and the API is pretty much the same as far as I know (because it is the mongodb API), so probably this is not a question I must answer since I don't know how AloeDB internals work.
 
This project is in stand by... I don't have enough time to work on DnDB but sure I don't want to let it die. Sadly I don't have enough maintainers either, so the DnDB's development will continue when I have enough time to work in my personal projects :/ . 

**A hope for DnDB**: The version we have WIP right is incredible fast, and the internals are partially refracted, to be exact the new driver is 6 times faster than NeDB for node. It needs more work to release launch a stable version.

So, you sure can use DnDB, but if you want somenthing that is maintained, you should use Aloe.
